# Docker file to couple frontend, backend, MySQL database,
# nGinx reverse proxy, and ACME LetsEncrypt instances into one.

# Replace the aista.com parts with your own domain
# Then create two DNS A records pointing to the IP address of
# your server. Content of DNS records should be 'magic-api' and 'magic'.

version: "2"

services:

  # This is the internet facing reverse proxy that routes
  # requests to your specific part, backend/frontend/etc.
  # This is the only thing that's actually exposed to the internet.
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf
    networks:
      - proxy
    restart: unless-stopped

  # This is the container that is responsible for retrieving
  # and renewing SSL certificates from LetsEncrypt
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    restart: unless-stopped

  # Our MySQL database
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ThisIsNotAGoodPassword
    volumes:
      - database:/var/lib/mysql
    networks:
      - proxy
    restart: unless-stopped

  # Our Magic backend
  backend:
    image: servergardens/magic-backend:latest
    container_name: backend
    depends_on:
      - db
      - acme-companion
      - nginx-proxy
    volumes:
      - etc_magic_folder:/magic/files/etc
      - modules_magic_folder:/magic/files/modules
      - config_magic_folder:/magic/config
    environment:
      # REPLACE THESE NEXT 3 PARTS WITH YOUR OWN DOMAIN/EMAIL
      - VIRTUAL_HOST=magic-api.aista.com
      - LETSENCRYPT_HOST=magic-api.aista.com
      - LETSENCRYPT_EMAIL=th@aista.com
    networks:
      - proxy
    restart: unless-stopped

  # Our Magic frontend (dashboard)
  frontend:
    image: servergardens/magic-frontend:latest
    container_name: frontend
    depends_on:
      - backend
    environment:

      # REPLACE THESE NEXT 3 PARTS WITH YOUR OWN DOMAIN/EMAIL
      - VIRTUAL_HOST=magic.aista.com
      - LETSENCRYPT_HOST=magic.aista.com
      - LETSENCRYPT_EMAIL=th@aista.com
    networks:
      - proxy
    restart: unless-stopped

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
  database:
  etc_magic_folder:
  modules_magic_folder:
  config_magic_folder:

networks:
  proxy:
    external:
      name: nginx-proxy
